### ISSUE TITLE
В Каталоге при уменьшении кол-ва элементов до 0 не происходит удаления из корзины

### ISSUE THREAD

**Issue by MiWas13** [MiWas13/YaPracticumSprint13koh07#4]
Продукт остаётся "в корзине", но с кол-вом 0. Продукт должен переходить в состояние "не выбранный", должна отображаться кнопка "в корзину"
![image](https://github.com/MiWas13/YaPracticumSprint13koh07/assets/18617783/52f6d49c-9dea-458a-916c-25087bc38afe)

**Comment by avanisimov** [comment]
всё круто!
